[package]
name = "jpeg_compresstion"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.3"
ndarray-image = "0.3.0"
array2d = "0.2.1"